/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.screens;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import ui.interfaces.AccionJasperEntreCodigos;
import ui.viewmodel.ClienteViewModel;

/**
 * Formulario modal para generar reportes JasperReports filtrados por un rango de códigos.
 * 
 * <p>Esta ventana permite al usuario especificar dos códigos (inicial y final) para
 * generar reportes que incluyan únicamente los registros dentro de ese rango.
 * La ventana valida en tiempo real que los códigos sean válidos y que el segundo
 * sea mayor o igual que el primero.</p>
 * 
 * <p>Esta clase utiliza el patrón Strategy mediante la interfaz {@link AccionJasperEntreCodigos},
 * lo que permite reutilizar este formulario para diferentes tipos de reportes (clientes,
 * artículos, proveedores, etc.) sin modificar su código. La acción específica a ejecutar
 * se inyecta mediante el constructor.</p>
 * 
 * @author tobias
 * @see AccionJasperEntreCodigos
 * @see ClienteViewModel#jasperClienteEntreCodigos(String, String)
 */
public class EntreCodigos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EntreCodigos.class.getName());
    
    // Almacena la acción específica a ejecutar cuando se genere el reporte (patrón Strategy)
    private final AccionJasperEntreCodigos accionJasper;

    /**
     * Crea una nueva instancia del formulario EntreCodigos.
     * 
     * <p>Este constructor configura la ventana para que:</p>
     * <ul>
     *   <li>Esté centrada en la pantalla</li>
     *   <li>No sea redimensionable</li>
     *   <li>Tenga desactivado el botón de cierre (solo se cierra con los botones Aceptar o Volver)</li>
     * </ul>
     * 
     * @param accionJasper La implementación de AccionJasperEntreCodigos que define
     *                     qué tipo de reporte se generará al pulsar Aceptar
     */
    public EntreCodigos(AccionJasperEntreCodigos accionJasper) {
        this.accionJasper = accionJasper;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); // Desaciva el boton de cerrar
        setLocationRelativeTo(null); 
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aceptarButton = new javax.swing.JButton();
        codigoUnoText = new javax.swing.JTextField();
        codigoDosText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        codigoUnoText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                codigoUnoTextCaretUpdate(evt);
            }
        });

        codigoDosText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                codigoDosTextCaretUpdate(evt);
            }
        });

        jLabel1.setText("-");

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(codigoUnoText, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoDosText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptarButton)
                    .addComponent(volverButton))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoUnoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoDosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aceptarButton)
                        .addGap(18, 18, 18)
                        .addComponent(volverButton)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // Valida los códigos ingresados y ejecuta el reporte si son correctos
        String text = "Errores en: \n";
        ArrayList<String> errores = new ArrayList<>();
        
        // Validación del primer código: debe ser exactamente 6 dígitos
        if (!(codigoCheck(codigoUnoText.getText()))){
                errores.add("Primer campo Invalido");
        }
        // Validación del segundo código: formato válido y debe ser >= al primero
        if (!(codigoCheck(codigoDosText.getText()) && Integer.parseInt(codigoUnoText.getText()) <= Integer.parseInt(codigoDosText.getText()))){
                errores.add("Formato inválido o el segundo código debe ser mayor o igual que el primero");
        }
        
        // Construcción del mensaje de error según la cantidad de errores
        if (errores.size()==1){
            text = "Error: ";
        }
        
        for (int i = 0; i < errores.size(); i++){
            if (i == errores.size()-1){
                text += errores.get(i);
            } else {
                text += errores.get(i) + ", ";
            }
        }
        
        
        if (!errores.isEmpty()) {
            JOptionPane.showMessageDialog(null, text, "Ventana Error", JOptionPane.YES_OPTION);
        } else {
            
           try {
               // Ejecución de la acción Jasper específica inyectada en el constructor
               accionJasper.ejecutar(codigoUnoText.getText(), codigoDosText.getText());
               JOptionPane.showMessageDialog(null, "Reporte generado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
           } catch (JRException ex) {
               System.getLogger(EntreCodigos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
           } catch (SQLException ex) {
               System.getLogger(EntreCodigos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
           }
            
           // Retorno al formulario de clientes (o el formulario que haya abierto esta ventana)
           FormCliente cliente = new FormCliente();
           cliente.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    /**
     * Valida en tiempo real el primer código y cambia el color del texto.
     * 
     * <p>Este listener se ejecuta cada vez que cambia el contenido del campo
     * codigoUnoText. Si el código es válido (6 dígitos), el texto se muestra
     * en negro; si es inválido, se muestra en rojo.</p>
     * 
     * @param evt El evento de actualización del cursor
     */
    private void codigoUnoTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_codigoUnoTextCaretUpdate
       String text = codigoUnoText.getText();
        if (codigoCheck(text)){
            codigoUnoText.setForeground(Color.BLACK);
        } else {
            codigoUnoText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_codigoUnoTextCaretUpdate

    /**
     * Valida el segundo código asegurando formato correcto y que sea &gt;= al primero.
     * 
     * <p>Este listener valida que el segundo código cumpla dos condiciones:</p>
     * <ul>
     *   <li>Tenga el formato correcto (6 dígitos numéricos)</li>
     *   <li>Sea mayor o igual que el primer código (para que el rango sea válido)</li>
     * </ul>
     * <p>Si ambas condiciones se cumplen, el texto se muestra en negro; si no, en rojo.</p>
     * 
     * @param evt El evento de actualización del cursor
     */
    private void codigoDosTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_codigoDosTextCaretUpdate
       String text = codigoDosText.getText();
        // Comparación numérica para asegurar que código2 >= código1
        if (!(codigoCheck(text) && Integer.parseInt(codigoUnoText.getText()) <= Integer.parseInt(text))){
            codigoDosText.setForeground(Color.RED);
        } else {
            codigoDosText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_codigoDosTextCaretUpdate

    /**
     * Cierra esta ventana y vuelve al formulario de clientes.
     * 
     * <p>Este método se ejecuta al pulsar el botón "Volver", cancelando
     * la generación del reporte y retornando al formulario principal.</p>
     * 
     * @param evt El evento de acción del botón
     */
    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        FormCliente cliente = new FormCliente();
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    /**
     * Valida que el texto sea exactamente 6 dígitos numéricos.
     * 
     * <p>Este método verifica que el código proporcionado cumpla con el formato
     * requerido: exactamente 6 caracteres, todos ellos dígitos del 0 al 9.</p>
     * 
     * @param text El texto a validar
     * @return true si el texto cumple el patrón [0-9]{6}, false en caso contrario
     */
    public static boolean codigoCheck(String text){
        return text.matches("[0-9]{6}");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JTextField codigoDosText;
    private javax.swing.JTextField codigoUnoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
