/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.screens;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import ui.interfaces.AccionJasperEntreCodigos;
import ui.viewmodel.ClienteViewModel;

/**
 *
 * @author tobias
 */
public class EntreCodigos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EntreCodigos.class.getName());
    private AccionJasperEntreCodigos accionJasper;

    /**
     * Creates new form EntreCodigos
     */
    public EntreCodigos(AccionJasperEntreCodigos accionJasper) {
        this.accionJasper = accionJasper;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); // Desaciva el boton de cerrar
        setLocationRelativeTo(null); 
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aceptarButton = new javax.swing.JButton();
        codigoUnoText = new javax.swing.JTextField();
        codigoDosText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        codigoUnoText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                codigoUnoTextCaretUpdate(evt);
            }
        });

        codigoDosText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                codigoDosTextCaretUpdate(evt);
            }
        });

        jLabel1.setText("-");

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(codigoUnoText, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoDosText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptarButton)
                    .addComponent(volverButton))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoUnoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoDosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aceptarButton)
                        .addGap(18, 18, 18)
                        .addComponent(volverButton)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        String text = "Errores en: \n";
        ArrayList<String> errores = new ArrayList<>();
        
        if (!(codigoCheck(codigoUnoText.getText()))){
                errores.add("Primer campo Invalido");
        }
        if (!(codigoCheck(codigoDosText.getText()) && Integer.parseInt(codigoUnoText.getText()) <= Integer.parseInt(codigoDosText.getText()))){
                errores.add("Formato inválido o el segundo código debe ser mayor o igual que el primero");
        }
        
        if (errores.size()==1){
            text = "Error: ";
        }
        
        for (int i = 0; i < errores.size(); i++){
            if (i == errores.size()-1){
                text += errores.get(i);
            } else {
                text += errores.get(i) + ", ";
            }
        }
        
        
        if (!errores.isEmpty()) {
            JOptionPane.showMessageDialog(null, text, "Ventana Error", JOptionPane.YES_OPTION);
        } else {
            
           try {
               accionJasper.ejecutar(codigoUnoText.getText(), codigoDosText.getText());
               JOptionPane.showMessageDialog(null, "Reporte generado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
           } catch (JRException ex) {
               System.getLogger(EntreCodigos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
           } catch (SQLException ex) {
               System.getLogger(EntreCodigos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
           }
            
           FormCliente cliente = new FormCliente();
           cliente.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void codigoUnoTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_codigoUnoTextCaretUpdate
       String text = codigoUnoText.getText();
        if (codigoCheck(text)){
            codigoUnoText.setForeground(Color.BLACK);
        } else {
            codigoUnoText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_codigoUnoTextCaretUpdate

    private void codigoDosTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_codigoDosTextCaretUpdate
       String text = codigoDosText.getText();
        if (!(codigoCheck(text) && Integer.parseInt(codigoUnoText.getText()) <= Integer.parseInt(text))){
            codigoDosText.setForeground(Color.RED);
        } else {
            codigoDosText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_codigoDosTextCaretUpdate

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        FormCliente cliente = new FormCliente();
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    public static boolean codigoCheck(String text){
        return text.matches("[0-9]{6}");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JTextField codigoDosText;
    private javax.swing.JTextField codigoUnoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
