/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.screens;

import data.model.Articulo;
import data.model.Cliente;
import data.model.Pedido;
import data.model.Proveedor;
import excepciones.ArticuloNotFoundException;
import excepciones.ClienteNotFoundException;
import excepciones.DataAccessException;
import excepciones.ProveedorNotFoundException;
import excepciones.StockNotEnoughtException;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ui.viewmodel.ArticuloViewModel;
import ui.viewmodel.ClienteViewModel;
import ui.viewmodel.ProveedorViewModel;

/**
 *
 * @author tobias
 */
public class FormPedido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPedido.class.getName());
    private enum Modo {CLIENTE, PROVEEDOR, NULO}
    private Modo modo;
    private ClienteViewModel vmC = new ClienteViewModel();
    private ProveedorViewModel vmP = new ProveedorViewModel();
    private ArticuloViewModel vmA = new ArticuloViewModel();
    private ArrayList<Pedido> lPedidos = new ArrayList<>();
    private Articulo articuloActual;



    /**
     * Creates new form FormPedidos
     */
    public FormPedido() {
        initComponents();
        
        allFieldEnabled(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); // Desaciva el boton de cerrar
        setLocationRelativeTo(null); // Centra la ventana al inizializar
        setResizable(false); // Desactiva el redimensionamiento
    }
    
   /**
     * Habilita los campos necesarios para las bases de datos, True or False
     * @param activar
     */
    public void allFieldEnabled(Boolean activar){
        codigoText.setEnabled(activar);
        articuloCodigo.setEnabled(activar);
        unidadesText.setEnabled(activar);
        aceptarButton.setEnabled(activar);
        facturaButton.setEnabled(activar);
        salirButton.setEnabled(activar);
        cancelTodoButton.setEnabled(activar);
        CancelarPedido.setEnabled(activar);
    }
   
    
    /*
    // Habilita los campos necesarios para las bases de datos 
    public void modoForm(){
        codigoText.setEnabled(true);
        aceptarButton.setEnabled(true);
        cancelTodoButton.setEnabled(true);
        salirButton.setEnabled(true);
    }
    */
    
    /**
     * Habilita la edicion de los campos jText, True or False
     * @param activar
     */     
    public void habilitarEdicion(Boolean activar){
        nifnText.setEditable(activar);
        nombreText.setEditable(activar);
        apellidosText.setEditable(activar);
        domicilioText.setEditable(activar); 
        cpText.setEditable(activar);
        localidadText.setEditable(activar);
    }
    
    public void focoCodigo(){
        codigoText.setEnabled(true);
        codigoText.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreText = new javax.swing.JTextField();
        cpText = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        domicilioText = new javax.swing.JTextField();
        cancelTodoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();
        localidadText = new javax.swing.JTextField();
        apellidosText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        salirButton = new javax.swing.JButton();
        niflText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nifnText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        articuloCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        unidadesText = new javax.swing.JTextField();
        descripcionText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stockText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        precioText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        importeText = new javax.swing.JTextField();
        facturaButton = new javax.swing.JButton();
        CancelarPedido = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        clientesMenu = new javax.swing.JMenuItem();
        proveedoresMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        volverMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreText.setEditable(false);
        nombreText.setEnabled(false);

        cpText.setEditable(false);
        cpText.setEnabled(false);

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        domicilioText.setEditable(false);
        domicilioText.setEnabled(false);

        cancelTodoButton.setText("Cancelar Todo");
        cancelTodoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTodoButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("N.I.F.");

        totalText.setEditable(false);
        totalText.setEnabled(false);

        localidadText.setEditable(false);
        localidadText.setEnabled(false);

        apellidosText.setEditable(false);
        apellidosText.setEnabled(false);

        jLabel12.setText("Total");

        jLabel5.setText("Domicilio");

        jLabel3.setText("Nombre");

        jLabel7.setText("Localidad");

        codigoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        niflText.setEditable(false);
        niflText.setEnabled(false);

        jLabel4.setText("Apellidos");

        nifnText.setEditable(false);
        nifnText.setEnabled(false);

        jLabel6.setText("C.P.");

        jSeparator2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        articuloCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articuloCodigoActionPerformed(evt);
            }
        });

        jLabel8.setText("Artículo");

        jLabel9.setText("Unidades");

        unidadesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadesTextActionPerformed(evt);
            }
        });

        descripcionText.setEditable(false);
        descripcionText.setEnabled(false);

        jLabel10.setText("Descripción");

        jLabel11.setText("Stock");

        stockText.setEditable(false);
        stockText.setEnabled(false);

        jLabel13.setText("Precio");

        precioText.setEditable(false);
        precioText.setEnabled(false);

        jLabel14.setText("Importe");

        importeText.setEditable(false);
        importeText.setEnabled(false);

        facturaButton.setText("Factura");
        facturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaButtonActionPerformed(evt);
            }
        });

        CancelarPedido.setText("Cancelar Pedido");
        CancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarPedidoActionPerformed(evt);
            }
        });

        jMenu1.setText("pedidos");

        clientesMenu.setText("Clientes");
        clientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesMenuActionPerformed(evt);
            }
        });
        jMenu1.add(clientesMenu);

        proveedoresMenu.setText("Proveedores");
        proveedoresMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresMenuActionPerformed(evt);
            }
        });
        jMenu1.add(proveedoresMenu);
        jMenu1.add(jSeparator1);

        volverMenu.setText("Volver");
        volverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuActionPerformed(evt);
            }
        });
        jMenu1.add(volverMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(articuloCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(descripcionText, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(localidadText))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nifnText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(niflText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(nombreText)))
                            .addComponent(apellidosText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(domicilioText, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(unidadesText, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(stockText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(precioText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(importeText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(CancelarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelTodoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(facturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nifnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(niflText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(apellidosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(domicilioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(localidadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(articuloCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descripcionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidadesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(precioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stockText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(importeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(aceptarButton)
                                .addComponent(facturaButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelTodoButton)
                            .addComponent(CancelarPedido))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        boolean existe = false;
        
        try{
            Pedido p = new Pedido(articuloCodigo.getText(), Integer.valueOf(unidadesText.getText()), Float.valueOf(stockText.getText()), Float.valueOf(precioText.getText()), Float.valueOf(importeText.getText()));
            
            float stockDisponible = calcularStockDisponible(articuloActual);
            if ((p.getUnidades() > stockDisponible) && modo == Modo.CLIENTE){ 
                throw new StockNotEnoughtException("Stock sobre pasado");
            }

            for (Pedido pedido : lPedidos) {
                if (!pedido.getCodigoArticulo().equals(p.getCodigoArticulo())) {
                    continue;
                }

                if (modo == Modo.CLIENTE) {
                    int unidadesTotales = pedido.getUnidades() + p.getUnidades();
                    if (pedido.getStock() < unidadesTotales) {
                        throw new StockNotEnoughtException("No hay suficiente stock disponible");
                    }
                }

                pedido.setUnidades(pedido.getUnidades() + p.getUnidades());
                pedido.setPrecioCantidad(pedido.getPrecioCantidad() + p.getPrecioCantidad());
                existe = true;
            }
            
            if(!existe) lPedidos.add(p);
        }  catch (StockNotEnoughtException e) {
            JOptionPane.showMessageDialog(null, "No hay suficiente stock en el almacen");
        }
        
        resetDown();
        unidadesText.setEnabled(false);
        enableButtons(true);
        
        aceptarButton.setEnabled(false);
        
        articuloCodigo.setEnabled(true);
        articuloCodigo.grabFocus();
        CancelarPedido.setEnabled(false);
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void cancelTodoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTodoButtonActionPerformed
        resetAll();
        lPedidos.clear();
        allFieldEnabled(false);
        salirButton.setEnabled(true);
        codigoText.setEnabled(true);
        codigoText.setEditable(true);
        codigoText.grabFocus();
    }//GEN-LAST:event_cancelTodoButtonActionPerformed

    private void codigoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextActionPerformed
 try {
            // Verifica que en modo MODIFICACIONES, exista el articulo en la db
            if(modo == Modo.CLIENTE && codigoCheck(codigoText.getText())){
                Cliente cliente = vmC.consultaPorCodigo(codigoText.getText());

                nifnText.setText(cliente.getNif().substring(0, cliente.getNif().length() - 1));
                apellidosText.setText(cliente.getApellidos());
                nombreText.setText(cliente.getNombre());
                cpText.setText(cliente.getCodigoPostal());
                localidadText.setText(cliente.getLocalidad());
                domicilioText.setText(cliente.getDomicilio());
                totalText.setText(String.valueOf(cliente.getTotal()));

                codigoText.setEditable(false);
                articuloCodigo.setEnabled(true);
                articuloCodigo.grabFocus();
                cancelTodoButton.setEnabled(true);
            } else if(modo == Modo.PROVEEDOR && codigoCheck(codigoText.getText())){
                
                Proveedor proveedor = vmP.consultaPorCodigo(codigoText.getText());

                nifnText.setText(proveedor.getNif().substring(0, proveedor.getNif().length() - 1));
                apellidosText.setText(proveedor.getApellidos());
                nombreText.setText(proveedor.getNombre()); 
                cpText.setText(proveedor.getCodigoPostal()); 
                localidadText.setText(proveedor.getLocalidad());
                domicilioText.setText(proveedor.getDomicilio());
                totalText.setText(String.valueOf(proveedor.getTotal()));
                
                codigoText.setEditable(false);
                articuloCodigo.setEnabled(true);
                articuloCodigo.grabFocus();
                cancelTodoButton.setEnabled(true);
            }
        } catch (ProveedorNotFoundException ex) {
            codigoText.setText("");        
            JOptionPane.showMessageDialog(
                null,                       
                ex.getMessage(),     
                "Error",                    
                JOptionPane.ERROR_MESSAGE);
        }catch (ClienteNotFoundException ex) {
            codigoText.setText("");
            JOptionPane.showMessageDialog(
                null,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE );
        } catch(DataAccessException ex) {
            codigoText.setText("");
            JOptionPane.showMessageDialog(
                null,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            System.getLogger(FormCliente.class.getName()).log(System.Logger.Level.ERROR, "DB error", ex);
        }
    }//GEN-LAST:event_codigoTextActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        cambiarModo(Modo.NULO);
        lPedidos.clear();
        unidadesText.setEnabled(false);
    }//GEN-LAST:event_salirButtonActionPerformed

    private void proveedoresMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresMenuActionPerformed
        cambiarModo(Modo.PROVEEDOR);
        salirButton.setEnabled(true);
    }//GEN-LAST:event_proveedoresMenuActionPerformed

    private void volverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMenuActionPerformed

    private void clientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesMenuActionPerformed
        cambiarModo(Modo.CLIENTE);
        salirButton.setEnabled(true);        
    }//GEN-LAST:event_clientesMenuActionPerformed

    private void articuloCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articuloCodigoActionPerformed
        if (codigoCheck(articuloCodigo.getText())){
            try {
                Articulo articulo = vmA.consultaPorCodigo(articuloCodigo.getText());
                articuloActual = articulo;
                
                descripcionText.setText(articulo.getDescripcion());
                
                float stockDisponible = calcularStockDisponible(articulo);
                stockText.setText(String.valueOf(stockDisponible));
                if (modo == Modo.CLIENTE){
                    precioText.setText(String.valueOf(articulo.getPrecioVenta()));
                } else {
                    precioText.setText(String.valueOf(articulo.getPrecioCompra()));
                }   
                unidadesText.setEnabled(true);
                
                articuloCodigo.setEnabled(false);
                CancelarPedido.setEnabled(true);
                unidadesText.grabFocus();
            } catch (ArticuloNotFoundException ex) {
                articuloCodigo.setText("");            
                JOptionPane.showMessageDialog(
                    null,                       
                    ex.getMessage(),     
                    "Error",                    
                    JOptionPane.ERROR_MESSAGE );
            } catch(DataAccessException ex) {
                articuloCodigo.setText("");                    
                JOptionPane.showMessageDialog(
                    null, 
                    ex.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                System.getLogger(FormCliente.class.getName()).log(System.Logger.Level.ERROR, "DB error", ex);
            }
        } 
    }//GEN-LAST:event_articuloCodigoActionPerformed

    private void CancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarPedidoActionPerformed
        resetDown();
        articuloCodigo.setEnabled(true);
        unidadesText.setEnabled(false);
    }//GEN-LAST:event_CancelarPedidoActionPerformed

    private void unidadesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadesTextActionPerformed
        int ud = Integer.valueOf(unidadesText.getText());
        float precio = Float.valueOf(precioText.getText());
        
        float precioTotal = ud * precio;
        
        importeText.setText(String.valueOf(precioTotal));
        aceptarButton.setEnabled(true);
    }//GEN-LAST:event_unidadesTextActionPerformed

    private void facturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPedido().setVisible(true));
    }
    
    //metodo para Código
    public static boolean codigoCheck(String text){
        return text.matches("[0-9]{6}");
    }
    
    public boolean esFloat(String text) {
        if (text == null) return false;

        try {
            Float.valueOf(text);
            return true;
        } catch (NumberFormatException e) {
            return false;
    }
}
    
    
    public void resetAll(){
        codigoText.setText("");
        nifnText.setText("");
        nifnText.setText("");
        apellidosText.setText("");
        nombreText.setText("");
        domicilioText.setText("");
        cpText.setText("");
        localidadText.setText("");
        totalText.setText("");
        articuloCodigo.setText("");
        descripcionText.setText("");
        stockText.setText("");
        precioText.setText("");
        unidadesText.setText("");
        importeText.setText("");
    }
    
    public void cambiarModo(Modo modo){
        this.modo = modo;
        enableButtons(false);
        resetUp();
        resetDown();
        allFieldEnabled(false);
        lPedidos.clear();
        
        
        if (modo == Modo.CLIENTE) {
            facturaButton.setText("Factura");
        } else {
            facturaButton.setText("Finalizar");
        }
        
        
        if (modo != Modo.NULO){
            codigoText.setEnabled(true);
            codigoText.grabFocus();
            
        } else {
            codigoText.setEditable(true);
        }
    }
    
    private float calcularStockDisponible(Articulo articulo) {
        if (articulo == null) return 0;
        float stock = articulo.getStock();

        for (Pedido ped : lPedidos) {
            if (ped.getCodigoArticulo().equals(articulo.getCodigo())) {
                if (modo == Modo.CLIENTE) {
                    stock -= ped.getUnidades();
                } else {
                    stock += ped.getUnidades();
                }
            }
        }
        return stock;
    }
    
    
    public void mostrarCliente(Cliente cli){
        if (cli.getNif() != null){
            codigoText.setText(cli.getCodigo());
            nifnText.setText(cli.getNif());
            apellidosText.setText(cli.getApellidos());
            nombreText.setText(cli.getNombre());
            domicilioText.setText(cli.getDomicilio());
            cpText.setText(cli.getCodigoPostal());
            localidadText.setText(cli.getLocalidad());
            totalText.setText(String.valueOf(cli.getTotal()));
        }
    }
    
    //Muestra por pantalla el proveedor que se le pase por parametro
    public void mostrarProveedor(Proveedor pro){
        if (pro.getNif() != null){
            String numeroDNI = pro.getNif().substring(0, 8);
            codigoText.setText(pro.getCodigo());
            nifnText.setText(pro.getNif());
            apellidosText.setText(pro.getApellidos());
            nombreText.setText(pro.getNombre());
            domicilioText.setText(pro.getDomicilio());
            cpText.setText(pro.getCodigoPostal());
            localidadText.setText(pro.getLocalidad());
            totalText.setText(String.valueOf(pro.getTotal()));
        }
    }
    
    //Mostrar por pantalla el codigo
    public void mostrarArticulo(Articulo art){
        if (art.getCodigo() != null){
            articuloCodigo.setText(art.getCodigo());
            descripcionText.setText(art.getDescripcion());
            stockText.setText(String.valueOf(art.getStock()));
           
            if (modo==Modo.CLIENTE){
                precioText.setText(String.valueOf(art.getPrecioVenta()));
            } else {
                precioText.setText(String.valueOf(art.getPrecioCompra()));
            }          
        } else {
            System.out.println("Error");
        }
    }
    
    public void resetUp(){
        codigoText.setText("");
        nifnText.setText("");
        nifnText.setText("");
        apellidosText.setText("");
        nombreText.setText("");
        domicilioText.setText("");
        cpText.setText("");
        localidadText.setText("");
        totalText.setText("");
    }
    
    public void resetDown(){
        articuloCodigo.setText("");
        descripcionText.setText("");
        stockText.setText("");
        precioText.setText("");
        unidadesText.setText("");
        importeText.setText("");
        articuloActual = null;
    }
    
  
    public void enableButtons(boolean activar){
        aceptarButton.setEnabled(activar);
        facturaButton.setEnabled(activar);
        salirButton.setEnabled(activar);
        cancelTodoButton.setEnabled(activar);
        CancelarPedido.setEnabled(activar);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarPedido;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JTextField apellidosText;
    private javax.swing.JTextField articuloCodigo;
    private javax.swing.JButton cancelTodoButton;
    private javax.swing.JMenuItem clientesMenu;
    private javax.swing.JTextField codigoText;
    private javax.swing.JTextField cpText;
    private javax.swing.JTextField descripcionText;
    private javax.swing.JTextField domicilioText;
    private javax.swing.JButton facturaButton;
    private javax.swing.JTextField importeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField localidadText;
    private javax.swing.JTextField niflText;
    private javax.swing.JTextField nifnText;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextField precioText;
    private javax.swing.JMenuItem proveedoresMenu;
    private javax.swing.JButton salirButton;
    private javax.swing.JTextField stockText;
    private javax.swing.JTextField totalText;
    private javax.swing.JTextField unidadesText;
    private javax.swing.JMenuItem volverMenu;
    // End of variables declaration//GEN-END:variables
}
