/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.screens;

import data.model.Articulo;
import excepciones.ArticuloAlreadyExistsException;
import excepciones.ArticuloNotFoundException;
import excepciones.DataAccessException;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import ui.viewmodel.ArticuloViewModel;

/**
 *
 * @author jfeyj
 */
public class FormArticulo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormArticulo.class.getName());
    
    private enum Modo {ALTA, BAJA, MODIFICACIONES, CONSULTAPORCODIGO, ENTRECODIGOS, GRAFICOS};
    private Modo modo;
    private ArticuloViewModel vm = new ArticuloViewModel();
    
    /**
     * Creates new form Formulario
     */
    public FormArticulo() {
        initComponents();
        
        
        desactivateAll();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); // Desaciva el boton de cerrar        
        setLocationRelativeTo(null); // Centra la ventana al inizializar
        setResizable(false); // Desactiva el redimensionamiento


    }
    
    public void desactivateAll(){
        codigoText.setEnabled(false);
        stockText.setEnabled(false);
        stockMinText.setEnabled(false);
        precioCompraText.setEnabled(false);
        PrecioVentaText.setEnabled(false); 
        descripcionText.setEnabled(false);
        aceptarButton.setEnabled(false);
        cancelButton.setEnabled(false);
        salirButton.setEnabled(false);
    }
    
    public void activateAll(){
        codigoText.setEnabled(true);
        stockText.setEnabled(true);
        stockMinText.setEnabled(true);
        precioCompraText.setEnabled(true);
        PrecioVentaText.setEnabled(true); 
        descripcionText.setEnabled(true);
        aceptarButton.setEnabled(true);
        cancelButton.setEnabled(true);
        salirButton.setEnabled(true);
    }
    
    // Habilita los campos necesarios para las bases de datos
    public void modoForm(){
        codigoText.setEnabled(true);
        aceptarButton.setEnabled(true);
        cancelButton.setEnabled(true);
        salirButton.setEnabled(true);
    }
    
    public void deshabilitarEdicion(){
        stockText.setEditable(false);
        stockMinText.setEditable(false);
        precioCompraText.setEditable(false);
        PrecioVentaText.setEditable(false); 
        descripcionText.setEditable(false);
    }
    
     public void habilitarEdicion(){
        stockText.setEditable(true);
        stockMinText.setEditable(true);
        precioCompraText.setEditable(true);
        PrecioVentaText.setEditable(true); 
        descripcionText.setEditable(true);
    }
    
    public void focoCodigo(){
        codigoText.setEnabled(true);
        codigoText.requestFocus();
    }
     
    public void preparacionModos(){
        reset();
        desactivateAll();
        habilitarEdicion();
        modoForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        codigoText = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salirButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionText = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        stockText = new javax.swing.JTextField();
        stockMinText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precioCompraText = new javax.swing.JTextField();
        PrecioVentaText = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        altasMenu = new javax.swing.JMenuItem();
        bajasMenu = new javax.swing.JMenuItem();
        modificacionesMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        volverMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        porCodigoMenu = new javax.swing.JMenuItem();
        porCodigoMenuV2 = new javax.swing.JMenu();
        ListadoPorCodigoJasper = new javax.swing.JMenuItem();
        entreCodigosMenu = new javax.swing.JMenuItem();
        graficoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prueba de entrada de datos");

        codigoText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                codigoTextCaretUpdate(evt);
            }
        });
        codigoText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoTextFocusLost(evt);
            }
        });

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel5.setText("Descripcion");

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        descripcionText.setColumns(20);
        descripcionText.setRows(5);
        descripcionText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                descripcionTextCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(descripcionText);

        jLabel13.setText("Stock");

        stockText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                stockTextCaretUpdate(evt);
            }
        });
        stockText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockTextActionPerformed(evt);
            }
        });

        stockMinText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                stockMinTextCaretUpdate(evt);
            }
        });
        stockMinText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMinTextActionPerformed(evt);
            }
        });

        jLabel14.setText("Stock Minimo");

        jLabel2.setText("Precio Compra");

        jLabel3.setText("Precio Venta");

        precioCompraText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                precioCompraTextCaretUpdate(evt);
            }
        });
        precioCompraText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCompraTextActionPerformed(evt);
            }
        });

        PrecioVentaText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                PrecioVentaTextCaretUpdate(evt);
            }
        });
        PrecioVentaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioVentaTextActionPerformed(evt);
            }
        });

        jMenu2.setText("Mantenimiento");

        altasMenu.setText("Altas");
        altasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altasMenuActionPerformed(evt);
            }
        });
        jMenu2.add(altasMenu);

        bajasMenu.setText("Bajas");
        bajasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajasMenuActionPerformed(evt);
            }
        });
        jMenu2.add(bajasMenu);

        modificacionesMenu.setText("Modificaciones");
        modificacionesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificacionesMenuActionPerformed(evt);
            }
        });
        jMenu2.add(modificacionesMenu);
        jMenu2.add(jSeparator2);

        volverMenu.setText("Volver");
        volverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuActionPerformed(evt);
            }
        });
        jMenu2.add(volverMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        porCodigoMenu.setText("Por código");
        porCodigoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porCodigoMenuActionPerformed(evt);
            }
        });
        jMenu3.add(porCodigoMenu);

        porCodigoMenuV2.setText("Listados");

        ListadoPorCodigoJasper.setText("Por código");
        ListadoPorCodigoJasper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoPorCodigoJasperActionPerformed(evt);
            }
        });
        porCodigoMenuV2.add(ListadoPorCodigoJasper);

        entreCodigosMenu.setText("Entre códigos");
        entreCodigosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreCodigosMenuActionPerformed(evt);
            }
        });
        porCodigoMenuV2.add(entreCodigosMenu);

        graficoMenu.setText("Gráficos");
        graficoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficoMenuActionPerformed(evt);
            }
        });
        porCodigoMenuV2.add(graficoMenu);

        jMenu3.add(porCodigoMenuV2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stockMinText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(stockText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(precioCompraText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 105, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(PrecioVentaText, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(aceptarButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stockText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stockMinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioCompraText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrecioVentaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aceptarButton)
                            .addComponent(cancelButton)
                            .addComponent(salirButton))
                        .addGap(16, 16, 16))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        reset();
        desactivateAll();
        focoCodigo();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed

        String text = "Errores en: \n";
        ArrayList<String> errores = new ArrayList<>();

        switch(modo){
            case BAJA, CONSULTAPORCODIGO:
                if (!(codigoCheck(codigoText.getText()))){
                errores.add("Código");
                }
                break;
            default: 
               if (!(codigoCheck(codigoText.getText()))){
                errores.add("Código");
                }
        } 
        
            
        
        if (errores.size()==1){
            text = "Error en: ";
        }
        
        for (int i = 0; i < errores.size(); i++){
            if (i == errores.size()-1){
                text += errores.get(i);
            } else {
                text += errores.get(i) + ", ";
            }
        }
        
        
        if (!errores.isEmpty()) {
            jOptionPane1.showMessageDialog(null, text, "Ventana Error", jOptionPane1.YES_OPTION);
            
        } else {
            try{
                switch(modo) {
                    case ALTA:
                           vm.altaArticulo(
                                   codigoText.getText(),
                                   descripcionText.getText(),
                                   Float.parseFloat(stockText.getText()),
                                   Float.parseFloat(stockMinText.getText()),
                                   Float.parseFloat(precioCompraText.getText()),
                                   Float.parseFloat(PrecioVentaText.getText())
                           );

                        reset();
                        desactivateAll();
                        break; 
                    case BAJA:
                            vm.bajaArticulo(codigoText.getText());

                            JOptionPane.showMessageDialog(
                                null,                         
                                "Cliente eliminado con exito", 
                                "Información",                
                                JOptionPane.INFORMATION_MESSAGE 
                            );

                        reset();
                        break; 
                    case MODIFICACIONES: 
                            vm.modificarArticulo(
                                   codigoText.getText(),
                                   descripcionText.getText(),
                                   Float.parseFloat(stockText.getText()),
                                   Float.parseFloat(stockMinText.getText()),
                                   Float.parseFloat(precioCompraText.getText()),
                                   Float.parseFloat(PrecioVentaText.getText())
                           );
                            JOptionPane.showMessageDialog(
                                null,                         
                                "Cliente modificado con exito", 
                                "Información",                
                                JOptionPane.INFORMATION_MESSAGE 
                            );

                        reset();
                        desactivateAll();
                        break; 
                    case CONSULTAPORCODIGO:
                            Articulo articulo = vm.consultaPorCodigo(codigoText.getText());
                            descripcionText.setText(articulo.getDescripcion());
                            stockText.setText(String.valueOf(articulo.getStock()));
                            stockText.setText(String.valueOf(articulo.getStock()));
                            stockMinText.setText(String.valueOf(articulo.getStock()));
                            precioCompraText.setText(String.valueOf(articulo.getStock()));
                            PrecioVentaText.setText(String.valueOf(articulo.getStock()));

                        break;
                        
                } 
            } catch (ArticuloAlreadyExistsException ex) {
                codigoText.setText("");                    
                JOptionPane.showMessageDialog(
                    null,                       
                    ex.getMessage(),     
                    "Error",                    
                    JOptionPane.ERROR_MESSAGE );
            } catch (ArticuloNotFoundException ex) {
                codigoText.setText("");                    
                JOptionPane.showMessageDialog(
                    null,                       
                    ex.getMessage(),     
                    "Error",                    
                    JOptionPane.ERROR_MESSAGE );
            } catch(DataAccessException ex) {
                codigoText.setText("");                    
                JOptionPane.showMessageDialog(
                        null, 
                        ex.getMessage(), 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE
                );
                System.getLogger(FormCliente.class.getName()).log(System.Logger.Level.ERROR, "DB error", ex);
            }
        } 
        focoCodigo();
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void codigoTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_codigoTextCaretUpdate
        String text = codigoText.getText();
        if (codigoCheck(text)){
            codigoText.setForeground(Color.BLACK);
            if(modo != Modo.BAJA && modo != Modo.CONSULTAPORCODIGO){
                activateAll();
            }
            
        } else {
            codigoText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_codigoTextCaretUpdate

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        reset();
        desactivateAll();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void volverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMenuActionPerformed

    private void altasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altasMenuActionPerformed
        modo = Modo.ALTA;
        preparacionModos();

    }//GEN-LAST:event_altasMenuActionPerformed

    private void bajasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajasMenuActionPerformed
        preparacionModos();
        modo = Modo.BAJA;
    }//GEN-LAST:event_bajasMenuActionPerformed

    private void modificacionesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificacionesMenuActionPerformed
        preparacionModos();
        modo = Modo.MODIFICACIONES;
    }//GEN-LAST:event_modificacionesMenuActionPerformed

    private void porCodigoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porCodigoMenuActionPerformed
        preparacionModos();
        modo = Modo.CONSULTAPORCODIGO;  
    }//GEN-LAST:event_porCodigoMenuActionPerformed

    private void entreCodigosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreCodigosMenuActionPerformed
        desactivateAll();        
        EntreCodigos ec = new EntreCodigos( 
          (cod1, cod2) -> {
            try {
                vm.jasperArticuloEntreCodigos(cod1, cod2);
            } catch (JRException ex) {
                System.getLogger(FormArticulo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (SQLException ex) {
                System.getLogger(FormArticulo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (DataAccessException ex) {
                System.getLogger(FormArticulo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        );
        ec.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_entreCodigosMenuActionPerformed

    private void graficoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficoMenuActionPerformed
        desactivateAll();        
    }//GEN-LAST:event_graficoMenuActionPerformed

    private void ListadoPorCodigoJasperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoPorCodigoJasperActionPerformed
        desactivateAll();        
        try {
            vm.jasperArticuloPorCodigo();
            JOptionPane.showMessageDialog(
                        null,                       
                        "¡PDF descargado correctamente!",     
                        "Realizado",                    
                        JOptionPane.INFORMATION_MESSAGE 
                    );
        } catch (JRException | SQLException ex) {
            System.getLogger(FormCliente.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (DataAccessException ex) {
            System.getLogger(FormArticulo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_ListadoPorCodigoJasperActionPerformed

    private void stockMinTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMinTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMinTextActionPerformed

    private void stockTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTextActionPerformed

    private void precioCompraTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCompraTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioCompraTextActionPerformed

    private void PrecioVentaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioVentaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioVentaTextActionPerformed

    private void stockTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_stockTextCaretUpdate
        String text = stockText.getText();
        if (esFloat(text)){
            stockText.setForeground(Color.BLACK);
        } else {
            stockText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_stockTextCaretUpdate

    private void stockMinTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_stockMinTextCaretUpdate
        String text = stockMinText.getText();
        if (esFloat(text)){
            stockMinText.setForeground(Color.BLACK);
        } else {
            stockMinText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_stockMinTextCaretUpdate

    private void precioCompraTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_precioCompraTextCaretUpdate
        String text = precioCompraText.getText();
        if (esFloat(text)){
            precioCompraText.setForeground(Color.BLACK);
        } else {
            precioCompraText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_precioCompraTextCaretUpdate

    private void PrecioVentaTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_PrecioVentaTextCaretUpdate
        String text = PrecioVentaText.getText();
        if (esFloat(text)){
            PrecioVentaText.setForeground(Color.BLACK);
        } else {
            PrecioVentaText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_PrecioVentaTextCaretUpdate

    private void descripcionTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_descripcionTextCaretUpdate
        String text = descripcionText.getText();
        if (descripcionCheck(text)){
            descripcionText.setForeground(Color.BLACK);
        } else {
            descripcionText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_descripcionTextCaretUpdate

    private void codigoTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoTextFocusLost
        if(modo == Modo.MODIFICACIONES && codigoCheck(codigoText.getText())){
            try {
                Articulo articulo = vm.consultaPorCodigo(codigoText.getText());
             } catch (ArticuloNotFoundException ex) {
                codigoText.setText("");                    
                JOptionPane.showMessageDialog(
                    null,                       
                    ex.getMessage(),     
                    "Error",                    
                    JOptionPane.ERROR_MESSAGE );
            } catch(DataAccessException ex) {
                codigoText.setText("");                    
                JOptionPane.showMessageDialog(
                        null, 
                        ex.getMessage(), 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE
                );
                System.getLogger(FormCliente.class.getName()).log(System.Logger.Level.ERROR, "DB error", ex);
            }
            codigoText.setForeground(Color.RED);                
        }
    }//GEN-LAST:event_codigoTextFocusLost

    public void ventanaEntreCodigos(){
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormArticulo().setVisible(true));
    }
    
    //metodo para Código
    public static boolean codigoCheck(String text){
        return text.matches("[0-9]{6}");
    }
    
    public static boolean descripcionCheck(String text){
            return text.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]{1,25}");
    }
    
    public boolean esFloat(String text) {
    if (text == null) return false;

    try {
        Float.valueOf(text);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}
   
    public void reset(){
        codigoText.grabFocus();
        codigoText.setText("");
        stockText.setText("");
        stockMinText.setText("");
        precioCompraText.setText("");
        PrecioVentaText.setText("");
        descripcionText.setText("");
        
    }
    public static void showOtherWindow(){
        
    }
    
    
    
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListadoPorCodigoJasper;
    private javax.swing.JTextField PrecioVentaText;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JMenuItem altasMenu;
    private javax.swing.JMenuItem bajasMenu;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField codigoText;
    private javax.swing.JTextArea descripcionText;
    private javax.swing.JMenuItem entreCodigosMenu;
    private javax.swing.JMenuItem graficoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem modificacionesMenu;
    private javax.swing.JMenuItem porCodigoMenu;
    private javax.swing.JMenu porCodigoMenuV2;
    private javax.swing.JTextField precioCompraText;
    private javax.swing.JButton salirButton;
    private javax.swing.JTextField stockMinText;
    private javax.swing.JTextField stockText;
    private javax.swing.JMenuItem volverMenu;
    // End of variables declaration//GEN-END:variables
}
